stages:
  data_ingestion:
    cmd: python src\data\data_ingestion.py
    deps:
    - src\data\data_ingestion.py
    outs:
    - data\raw\test_data.csv
    - data\raw\train_data.csv
    params:
    - data_ingestion.test_size
  data_preprocessing:
    cmd: python src\data\data_preprocessing.py
    deps:
    - data\raw\test_data.csv
    - data\raw\train_data.csv
    - src\data\data_preprocessing.py
    outs:
    - data\processed\train_data.csv
    - data\processed\test_data.csv
  feature_engineering:
    cmd: python src\features\features.py
    deps:
    - data\processed\test_data.csv
    - data\processed\train_data.csv
    - src\features\features.py
    outs:
    - data\interim\train_bow.csv
    - data\interim\test_bow.csv
    params:
    - feature_engineering.max_features
  modelling:
    cmd: python src\modelling\modelling.py
    deps:
    - data\interim\train_bow.csv
    - src\modelling\modelling.py
    outs:
    - models\random_forest_model.pkl
    params:
    - modelling.n_estimators
    - modelling.max_depth
  model_evaluation:
    cmd: python src\modelling\model_evaluation.py
    deps:
    - data\interim\test_bow.csv
    - src\modelling\model_evaluation.py
    - models\random_forest_model.pkl
    outs:
    - reports\metrics_hyperparameter.json


